// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: info.proto

package com.fula.yohee.pb;

public final class Info {
  private Info() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface BookMarkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:base.BookMark)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    java.util.List<com.fula.yohee.pb.Info.BookMark.Item> 
        getDataList();
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    com.fula.yohee.pb.Info.BookMark.Item getData(int index);
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    int getDataCount();
  }
  /**
   * Protobuf type {@code base.BookMark}
   */
  public  static final class BookMark extends
      com.google.protobuf.GeneratedMessageLite<
          BookMark, BookMark.Builder> implements
      // @@protoc_insertion_point(message_implements:base.BookMark)
      BookMarkOrBuilder {
    private BookMark() {
      data_ = emptyProtobufList();
    }
    public interface ItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:base.BookMark.Item)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      java.lang.String getTitle();
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <pre>
       *url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      java.lang.String getUrl();
      /**
       * <pre>
       *url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      com.google.protobuf.ByteString
          getUrlBytes();

      /**
       * <pre>
       *folder
       * </pre>
       *
       * <code>optional string folder = 3;</code>
       */
      java.lang.String getFolder();
      /**
       * <pre>
       *folder
       * </pre>
       *
       * <code>optional string folder = 3;</code>
       */
      com.google.protobuf.ByteString
          getFolderBytes();

      /**
       * <pre>
       *position
       * </pre>
       *
       * <code>optional uint32 position = 4;</code>
       */
      int getPosition();

      /**
       * <pre>
       *type, 0:bookmark, 1:pagemark
       * </pre>
       *
       * <code>optional uint32 type = 5;</code>
       */
      int getType();
    }
    /**
     * Protobuf type {@code base.BookMark.Item}
     */
    public  static final class Item extends
        com.google.protobuf.GeneratedMessageLite<
            Item, Item.Builder> implements
        // @@protoc_insertion_point(message_implements:base.BookMark.Item)
        ItemOrBuilder {
      private Item() {
        title_ = "";
        url_ = "";
        folder_ = "";
      }
      public static final int TITLE_FIELD_NUMBER = 1;
      private java.lang.String title_;
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      public java.lang.String getTitle() {
        return title_;
      }
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(title_);
      }
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      private void setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
      }
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      private void clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
      }
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      private void setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value.toStringUtf8();
      }

      public static final int URL_FIELD_NUMBER = 2;
      private java.lang.String url_;
      /**
       * <pre>
       *url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      public java.lang.String getUrl() {
        return url_;
      }
      /**
       * <pre>
       *url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(url_);
      }
      /**
       * <pre>
       *url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      private void setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
      }
      /**
       * <pre>
       *url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      private void clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
      }
      /**
       * <pre>
       *url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      private void setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value.toStringUtf8();
      }

      public static final int FOLDER_FIELD_NUMBER = 3;
      private java.lang.String folder_;
      /**
       * <pre>
       *folder
       * </pre>
       *
       * <code>optional string folder = 3;</code>
       */
      public java.lang.String getFolder() {
        return folder_;
      }
      /**
       * <pre>
       *folder
       * </pre>
       *
       * <code>optional string folder = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFolderBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(folder_);
      }
      /**
       * <pre>
       *folder
       * </pre>
       *
       * <code>optional string folder = 3;</code>
       */
      private void setFolder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        folder_ = value;
      }
      /**
       * <pre>
       *folder
       * </pre>
       *
       * <code>optional string folder = 3;</code>
       */
      private void clearFolder() {
        
        folder_ = getDefaultInstance().getFolder();
      }
      /**
       * <pre>
       *folder
       * </pre>
       *
       * <code>optional string folder = 3;</code>
       */
      private void setFolderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        folder_ = value.toStringUtf8();
      }

      public static final int POSITION_FIELD_NUMBER = 4;
      private int position_;
      /**
       * <pre>
       *position
       * </pre>
       *
       * <code>optional uint32 position = 4;</code>
       */
      public int getPosition() {
        return position_;
      }
      /**
       * <pre>
       *position
       * </pre>
       *
       * <code>optional uint32 position = 4;</code>
       */
      private void setPosition(int value) {
        
        position_ = value;
      }
      /**
       * <pre>
       *position
       * </pre>
       *
       * <code>optional uint32 position = 4;</code>
       */
      private void clearPosition() {
        
        position_ = 0;
      }

      public static final int TYPE_FIELD_NUMBER = 5;
      private int type_;
      /**
       * <pre>
       *type, 0:bookmark, 1:pagemark
       * </pre>
       *
       * <code>optional uint32 type = 5;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <pre>
       *type, 0:bookmark, 1:pagemark
       * </pre>
       *
       * <code>optional uint32 type = 5;</code>
       */
      private void setType(int value) {
        
        type_ = value;
      }
      /**
       * <pre>
       *type, 0:bookmark, 1:pagemark
       * </pre>
       *
       * <code>optional uint32 type = 5;</code>
       */
      private void clearType() {
        
        type_ = 0;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!title_.isEmpty()) {
          output.writeString(1, getTitle());
        }
        if (!url_.isEmpty()) {
          output.writeString(2, getUrl());
        }
        if (!folder_.isEmpty()) {
          output.writeString(3, getFolder());
        }
        if (position_ != 0) {
          output.writeUInt32(4, position_);
        }
        if (type_ != 0) {
          output.writeUInt32(5, type_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!title_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getTitle());
        }
        if (!url_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getUrl());
        }
        if (!folder_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(3, getFolder());
        }
        if (position_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(4, position_);
        }
        if (type_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(5, type_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static com.fula.yohee.pb.Info.BookMark.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.fula.yohee.pb.Info.BookMark.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.fula.yohee.pb.Info.BookMark.Item prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code base.BookMark.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.fula.yohee.pb.Info.BookMark.Item, Builder> implements
          // @@protoc_insertion_point(builder_implements:base.BookMark.Item)
          com.fula.yohee.pb.Info.BookMark.ItemOrBuilder {
        // Construct using com.fula.yohee.pb.Info.BookMark.Item.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public java.lang.String getTitle() {
          return instance.getTitle();
        }
        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          return instance.getTitleBytes();
        }
        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public Builder setTitle(
            java.lang.String value) {
          copyOnWrite();
          instance.setTitle(value);
          return this;
        }
        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public Builder clearTitle() {
          copyOnWrite();
          instance.clearTitle();
          return this;
        }
        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setTitleBytes(value);
          return this;
        }

        /**
         * <pre>
         *url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public java.lang.String getUrl() {
          return instance.getUrl();
        }
        /**
         * <pre>
         *url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          return instance.getUrlBytes();
        }
        /**
         * <pre>
         *url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public Builder setUrl(
            java.lang.String value) {
          copyOnWrite();
          instance.setUrl(value);
          return this;
        }
        /**
         * <pre>
         *url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public Builder clearUrl() {
          copyOnWrite();
          instance.clearUrl();
          return this;
        }
        /**
         * <pre>
         *url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setUrlBytes(value);
          return this;
        }

        /**
         * <pre>
         *folder
         * </pre>
         *
         * <code>optional string folder = 3;</code>
         */
        public java.lang.String getFolder() {
          return instance.getFolder();
        }
        /**
         * <pre>
         *folder
         * </pre>
         *
         * <code>optional string folder = 3;</code>
         */
        public com.google.protobuf.ByteString
            getFolderBytes() {
          return instance.getFolderBytes();
        }
        /**
         * <pre>
         *folder
         * </pre>
         *
         * <code>optional string folder = 3;</code>
         */
        public Builder setFolder(
            java.lang.String value) {
          copyOnWrite();
          instance.setFolder(value);
          return this;
        }
        /**
         * <pre>
         *folder
         * </pre>
         *
         * <code>optional string folder = 3;</code>
         */
        public Builder clearFolder() {
          copyOnWrite();
          instance.clearFolder();
          return this;
        }
        /**
         * <pre>
         *folder
         * </pre>
         *
         * <code>optional string folder = 3;</code>
         */
        public Builder setFolderBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setFolderBytes(value);
          return this;
        }

        /**
         * <pre>
         *position
         * </pre>
         *
         * <code>optional uint32 position = 4;</code>
         */
        public int getPosition() {
          return instance.getPosition();
        }
        /**
         * <pre>
         *position
         * </pre>
         *
         * <code>optional uint32 position = 4;</code>
         */
        public Builder setPosition(int value) {
          copyOnWrite();
          instance.setPosition(value);
          return this;
        }
        /**
         * <pre>
         *position
         * </pre>
         *
         * <code>optional uint32 position = 4;</code>
         */
        public Builder clearPosition() {
          copyOnWrite();
          instance.clearPosition();
          return this;
        }

        /**
         * <pre>
         *type, 0:bookmark, 1:pagemark
         * </pre>
         *
         * <code>optional uint32 type = 5;</code>
         */
        public int getType() {
          return instance.getType();
        }
        /**
         * <pre>
         *type, 0:bookmark, 1:pagemark
         * </pre>
         *
         * <code>optional uint32 type = 5;</code>
         */
        public Builder setType(int value) {
          copyOnWrite();
          instance.setType(value);
          return this;
        }
        /**
         * <pre>
         *type, 0:bookmark, 1:pagemark
         * </pre>
         *
         * <code>optional uint32 type = 5;</code>
         */
        public Builder clearType() {
          copyOnWrite();
          instance.clearType();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:base.BookMark.Item)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new com.fula.yohee.pb.Info.BookMark.Item();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            com.fula.yohee.pb.Info.BookMark.Item other = (com.fula.yohee.pb.Info.BookMark.Item) arg1;
            title_ = visitor.visitString(!title_.isEmpty(), title_,
                !other.title_.isEmpty(), other.title_);
            url_ = visitor.visitString(!url_.isEmpty(), url_,
                !other.url_.isEmpty(), other.url_);
            folder_ = visitor.visitString(!folder_.isEmpty(), folder_,
                !other.folder_.isEmpty(), other.folder_);
            position_ = visitor.visitInt(position_ != 0, position_,
                other.position_ != 0, other.position_);
            type_ = visitor.visitInt(type_ != 0, type_,
                other.type_ != 0, other.type_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readStringRequireUtf8();

                    title_ = s;
                    break;
                  }
                  case 18: {
                    String s = input.readStringRequireUtf8();

                    url_ = s;
                    break;
                  }
                  case 26: {
                    String s = input.readStringRequireUtf8();

                    folder_ = s;
                    break;
                  }
                  case 32: {

                    position_ = input.readUInt32();
                    break;
                  }
                  case 40: {

                    type_ = input.readUInt32();
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (com.fula.yohee.pb.Info.BookMark.Item.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:base.BookMark.Item)
      private static final com.fula.yohee.pb.Info.BookMark.Item DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Item();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static com.fula.yohee.pb.Info.BookMark.Item getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Item> PARSER;

      public static com.google.protobuf.Parser<Item> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.fula.yohee.pb.Info.BookMark.Item> data_;
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    public java.util.List<com.fula.yohee.pb.Info.BookMark.Item> getDataList() {
      return data_;
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    public java.util.List<? extends com.fula.yohee.pb.Info.BookMark.ItemOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    public com.fula.yohee.pb.Info.BookMark.Item getData(int index) {
      return data_.get(index);
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    public com.fula.yohee.pb.Info.BookMark.ItemOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    private void ensureDataIsMutable() {
      if (!data_.isModifiable()) {
        data_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(data_);
       }
    }

    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void setData(
        int index, com.fula.yohee.pb.Info.BookMark.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.set(index, value);
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void setData(
        int index, com.fula.yohee.pb.Info.BookMark.Item.Builder builderForValue) {
      ensureDataIsMutable();
      data_.set(index, builderForValue.build());
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void addData(com.fula.yohee.pb.Info.BookMark.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.add(value);
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void addData(
        int index, com.fula.yohee.pb.Info.BookMark.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.add(index, value);
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void addData(
        com.fula.yohee.pb.Info.BookMark.Item.Builder builderForValue) {
      ensureDataIsMutable();
      data_.add(builderForValue.build());
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void addData(
        int index, com.fula.yohee.pb.Info.BookMark.Item.Builder builderForValue) {
      ensureDataIsMutable();
      data_.add(index, builderForValue.build());
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void addAllData(
        java.lang.Iterable<? extends com.fula.yohee.pb.Info.BookMark.Item> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, data_);
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void clearData() {
      data_ = emptyProtobufList();
    }
    /**
     * <pre>
     *the bookmark items array.
     * </pre>
     *
     * <code>repeated .base.BookMark.Item data = 1;</code>
     */
    private void removeData(int index) {
      ensureDataIsMutable();
      data_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fula.yohee.pb.Info.BookMark parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fula.yohee.pb.Info.BookMark parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.BookMark parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fula.yohee.pb.Info.BookMark parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.BookMark parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.BookMark parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.BookMark parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.BookMark parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.BookMark parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.BookMark parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fula.yohee.pb.Info.BookMark prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code base.BookMark}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.fula.yohee.pb.Info.BookMark, Builder> implements
        // @@protoc_insertion_point(builder_implements:base.BookMark)
        com.fula.yohee.pb.Info.BookMarkOrBuilder {
      // Construct using com.fula.yohee.pb.Info.BookMark.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public java.util.List<com.fula.yohee.pb.Info.BookMark.Item> getDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataList());
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public int getDataCount() {
        return instance.getDataCount();
      }/**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public com.fula.yohee.pb.Info.BookMark.Item getData(int index) {
        return instance.getData(index);
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder setData(
          int index, com.fula.yohee.pb.Info.BookMark.Item value) {
        copyOnWrite();
        instance.setData(index, value);
        return this;
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder setData(
          int index, com.fula.yohee.pb.Info.BookMark.Item.Builder builderForValue) {
        copyOnWrite();
        instance.setData(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder addData(com.fula.yohee.pb.Info.BookMark.Item value) {
        copyOnWrite();
        instance.addData(value);
        return this;
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder addData(
          int index, com.fula.yohee.pb.Info.BookMark.Item value) {
        copyOnWrite();
        instance.addData(index, value);
        return this;
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder addData(
          com.fula.yohee.pb.Info.BookMark.Item.Builder builderForValue) {
        copyOnWrite();
        instance.addData(builderForValue);
        return this;
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder addData(
          int index, com.fula.yohee.pb.Info.BookMark.Item.Builder builderForValue) {
        copyOnWrite();
        instance.addData(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.fula.yohee.pb.Info.BookMark.Item> values) {
        copyOnWrite();
        instance.addAllData(values);
        return this;
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }
      /**
       * <pre>
       *the bookmark items array.
       * </pre>
       *
       * <code>repeated .base.BookMark.Item data = 1;</code>
       */
      public Builder removeData(int index) {
        copyOnWrite();
        instance.removeData(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:base.BookMark)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fula.yohee.pb.Info.BookMark();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          data_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fula.yohee.pb.Info.BookMark other = (com.fula.yohee.pb.Info.BookMark) arg1;
          data_= visitor.visitList(data_, other.data_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!data_.isModifiable()) {
                    data_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(data_);
                  }
                  data_.add(
                      input.readMessage(com.fula.yohee.pb.Info.BookMark.Item.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fula.yohee.pb.Info.BookMark.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:base.BookMark)
    private static final com.fula.yohee.pb.Info.BookMark DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new BookMark();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fula.yohee.pb.Info.BookMark getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<BookMark> PARSER;

    public static com.google.protobuf.Parser<BookMark> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HistoryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:base.History)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    java.util.List<com.fula.yohee.pb.Info.History.Item> 
        getDataList();
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    com.fula.yohee.pb.Info.History.Item getData(int index);
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    int getDataCount();
  }
  /**
   * Protobuf type {@code base.History}
   */
  public  static final class History extends
      com.google.protobuf.GeneratedMessageLite<
          History, History.Builder> implements
      // @@protoc_insertion_point(message_implements:base.History)
      HistoryOrBuilder {
    private History() {
      data_ = emptyProtobufList();
    }
    public interface ItemOrBuilder extends
        // @@protoc_insertion_point(interface_extends:base.History.Item)
        com.google.protobuf.MessageLiteOrBuilder {

      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      java.lang.String getTitle();
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      com.google.protobuf.ByteString
          getTitleBytes();

      /**
       * <pre>
       *link url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      java.lang.String getUrl();
      /**
       * <pre>
       *link url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      com.google.protobuf.ByteString
          getUrlBytes();

      /**
       * <pre>
       *time
       * </pre>
       *
       * <code>optional uint64 time = 3;</code>
       */
      long getTime();
    }
    /**
     * Protobuf type {@code base.History.Item}
     */
    public  static final class Item extends
        com.google.protobuf.GeneratedMessageLite<
            Item, Item.Builder> implements
        // @@protoc_insertion_point(message_implements:base.History.Item)
        ItemOrBuilder {
      private Item() {
        title_ = "";
        url_ = "";
      }
      public static final int TITLE_FIELD_NUMBER = 1;
      private java.lang.String title_;
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      public java.lang.String getTitle() {
        return title_;
      }
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(title_);
      }
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      private void setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
      }
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      private void clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
      }
      /**
       * <pre>
       *title
       * </pre>
       *
       * <code>optional string title = 1;</code>
       */
      private void setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value.toStringUtf8();
      }

      public static final int URL_FIELD_NUMBER = 2;
      private java.lang.String url_;
      /**
       * <pre>
       *link url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      public java.lang.String getUrl() {
        return url_;
      }
      /**
       * <pre>
       *link url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        return com.google.protobuf.ByteString.copyFromUtf8(url_);
      }
      /**
       * <pre>
       *link url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      private void setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
      }
      /**
       * <pre>
       *link url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      private void clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
      }
      /**
       * <pre>
       *link url
       * </pre>
       *
       * <code>optional string url = 2;</code>
       */
      private void setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value.toStringUtf8();
      }

      public static final int TIME_FIELD_NUMBER = 3;
      private long time_;
      /**
       * <pre>
       *time
       * </pre>
       *
       * <code>optional uint64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       *time
       * </pre>
       *
       * <code>optional uint64 time = 3;</code>
       */
      private void setTime(long value) {
        
        time_ = value;
      }
      /**
       * <pre>
       *time
       * </pre>
       *
       * <code>optional uint64 time = 3;</code>
       */
      private void clearTime() {
        
        time_ = 0L;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!title_.isEmpty()) {
          output.writeString(1, getTitle());
        }
        if (!url_.isEmpty()) {
          output.writeString(2, getUrl());
        }
        if (time_ != 0L) {
          output.writeUInt64(3, time_);
        }
      }

      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (!title_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(1, getTitle());
        }
        if (!url_.isEmpty()) {
          size += com.google.protobuf.CodedOutputStream
            .computeStringSize(2, getUrl());
        }
        if (time_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt64Size(3, time_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      public static com.fula.yohee.pb.Info.History.Item parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.fula.yohee.pb.Info.History.Item parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.fula.yohee.pb.Info.History.Item parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data);
      }
      public static com.fula.yohee.pb.Info.History.Item parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, data, extensionRegistry);
      }
      public static com.fula.yohee.pb.Info.History.Item parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.fula.yohee.pb.Info.History.Item parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.fula.yohee.pb.Info.History.Item parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input);
      }
      public static com.fula.yohee.pb.Info.History.Item parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
      }
      public static com.fula.yohee.pb.Info.History.Item parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input);
      }
      public static com.fula.yohee.pb.Info.History.Item parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageLite.parseFrom(
            DEFAULT_INSTANCE, input, extensionRegistry);
      }

      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.fula.yohee.pb.Info.History.Item prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }

      /**
       * Protobuf type {@code base.History.Item}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            com.fula.yohee.pb.Info.History.Item, Builder> implements
          // @@protoc_insertion_point(builder_implements:base.History.Item)
          com.fula.yohee.pb.Info.History.ItemOrBuilder {
        // Construct using com.fula.yohee.pb.Info.History.Item.newBuilder()
        private Builder() {
          super(DEFAULT_INSTANCE);
        }


        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public java.lang.String getTitle() {
          return instance.getTitle();
        }
        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTitleBytes() {
          return instance.getTitleBytes();
        }
        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public Builder setTitle(
            java.lang.String value) {
          copyOnWrite();
          instance.setTitle(value);
          return this;
        }
        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public Builder clearTitle() {
          copyOnWrite();
          instance.clearTitle();
          return this;
        }
        /**
         * <pre>
         *title
         * </pre>
         *
         * <code>optional string title = 1;</code>
         */
        public Builder setTitleBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setTitleBytes(value);
          return this;
        }

        /**
         * <pre>
         *link url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public java.lang.String getUrl() {
          return instance.getUrl();
        }
        /**
         * <pre>
         *link url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public com.google.protobuf.ByteString
            getUrlBytes() {
          return instance.getUrlBytes();
        }
        /**
         * <pre>
         *link url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public Builder setUrl(
            java.lang.String value) {
          copyOnWrite();
          instance.setUrl(value);
          return this;
        }
        /**
         * <pre>
         *link url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public Builder clearUrl() {
          copyOnWrite();
          instance.clearUrl();
          return this;
        }
        /**
         * <pre>
         *link url
         * </pre>
         *
         * <code>optional string url = 2;</code>
         */
        public Builder setUrlBytes(
            com.google.protobuf.ByteString value) {
          copyOnWrite();
          instance.setUrlBytes(value);
          return this;
        }

        /**
         * <pre>
         *time
         * </pre>
         *
         * <code>optional uint64 time = 3;</code>
         */
        public long getTime() {
          return instance.getTime();
        }
        /**
         * <pre>
         *time
         * </pre>
         *
         * <code>optional uint64 time = 3;</code>
         */
        public Builder setTime(long value) {
          copyOnWrite();
          instance.setTime(value);
          return this;
        }
        /**
         * <pre>
         *time
         * </pre>
         *
         * <code>optional uint64 time = 3;</code>
         */
        public Builder clearTime() {
          copyOnWrite();
          instance.clearTime();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:base.History.Item)
      }
      protected final Object dynamicMethod(
          com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
          Object arg0, Object arg1) {
        switch (method) {
          case NEW_MUTABLE_INSTANCE: {
            return new com.fula.yohee.pb.Info.History.Item();
          }
          case IS_INITIALIZED: {
            return DEFAULT_INSTANCE;
          }
          case MAKE_IMMUTABLE: {
            return null;
          }
          case NEW_BUILDER: {
            return new Builder();
          }
          case VISIT: {
            Visitor visitor = (Visitor) arg0;
            com.fula.yohee.pb.Info.History.Item other = (com.fula.yohee.pb.Info.History.Item) arg1;
            title_ = visitor.visitString(!title_.isEmpty(), title_,
                !other.title_.isEmpty(), other.title_);
            url_ = visitor.visitString(!url_.isEmpty(), url_,
                !other.url_.isEmpty(), other.url_);
            time_ = visitor.visitLong(time_ != 0L, time_,
                other.time_ != 0L, other.time_);
            if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
                .INSTANCE) {
            }
            return this;
          }
          case MERGE_FROM_STREAM: {
            com.google.protobuf.CodedInputStream input =
                (com.google.protobuf.CodedInputStream) arg0;
            com.google.protobuf.ExtensionRegistryLite extensionRegistry =
                (com.google.protobuf.ExtensionRegistryLite) arg1;
            try {
              boolean done = false;
              while (!done) {
                int tag = input.readTag();
                switch (tag) {
                  case 0:
                    done = true;
                    break;
                  default: {
                    if (!input.skipField(tag)) {
                      done = true;
                    }
                    break;
                  }
                  case 10: {
                    String s = input.readStringRequireUtf8();

                    title_ = s;
                    break;
                  }
                  case 18: {
                    String s = input.readStringRequireUtf8();

                    url_ = s;
                    break;
                  }
                  case 24: {

                    time_ = input.readUInt64();
                    break;
                  }
                }
              }
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
              throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (java.io.IOException e) {
              throw new RuntimeException(
                  new com.google.protobuf.InvalidProtocolBufferException(
                      e.getMessage()).setUnfinishedMessage(this));
            } finally {
            }
          }
          case GET_DEFAULT_INSTANCE: {
            return DEFAULT_INSTANCE;
          }
          case GET_PARSER: {
            if (PARSER == null) {    synchronized (com.fula.yohee.pb.Info.History.Item.class) {
                if (PARSER == null) {
                  PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
                }
              }
            }
            return PARSER;
          }
        }
        throw new UnsupportedOperationException();
      }


      // @@protoc_insertion_point(class_scope:base.History.Item)
      private static final com.fula.yohee.pb.Info.History.Item DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new Item();
        DEFAULT_INSTANCE.makeImmutable();
      }

      public static com.fula.yohee.pb.Info.History.Item getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static volatile com.google.protobuf.Parser<Item> PARSER;

      public static com.google.protobuf.Parser<Item> parser() {
        return DEFAULT_INSTANCE.getParserForType();
      }
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<com.fula.yohee.pb.Info.History.Item> data_;
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    public java.util.List<com.fula.yohee.pb.Info.History.Item> getDataList() {
      return data_;
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    public java.util.List<? extends com.fula.yohee.pb.Info.History.ItemOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    public com.fula.yohee.pb.Info.History.Item getData(int index) {
      return data_.get(index);
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    public com.fula.yohee.pb.Info.History.ItemOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }
    private void ensureDataIsMutable() {
      if (!data_.isModifiable()) {
        data_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(data_);
       }
    }

    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void setData(
        int index, com.fula.yohee.pb.Info.History.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.set(index, value);
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void setData(
        int index, com.fula.yohee.pb.Info.History.Item.Builder builderForValue) {
      ensureDataIsMutable();
      data_.set(index, builderForValue.build());
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void addData(com.fula.yohee.pb.Info.History.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.add(value);
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void addData(
        int index, com.fula.yohee.pb.Info.History.Item value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureDataIsMutable();
      data_.add(index, value);
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void addData(
        com.fula.yohee.pb.Info.History.Item.Builder builderForValue) {
      ensureDataIsMutable();
      data_.add(builderForValue.build());
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void addData(
        int index, com.fula.yohee.pb.Info.History.Item.Builder builderForValue) {
      ensureDataIsMutable();
      data_.add(index, builderForValue.build());
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void addAllData(
        java.lang.Iterable<? extends com.fula.yohee.pb.Info.History.Item> values) {
      ensureDataIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, data_);
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void clearData() {
      data_ = emptyProtobufList();
    }
    /**
     * <pre>
     *the history items array.
     * </pre>
     *
     * <code>repeated .base.History.Item data = 1;</code>
     */
    private void removeData(int index) {
      ensureDataIsMutable();
      data_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fula.yohee.pb.Info.History parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fula.yohee.pb.Info.History parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.History parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fula.yohee.pb.Info.History parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.History parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.History parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.History parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.History parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.History parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.History parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fula.yohee.pb.Info.History prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code base.History}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.fula.yohee.pb.Info.History, Builder> implements
        // @@protoc_insertion_point(builder_implements:base.History)
        com.fula.yohee.pb.Info.HistoryOrBuilder {
      // Construct using com.fula.yohee.pb.Info.History.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public java.util.List<com.fula.yohee.pb.Info.History.Item> getDataList() {
        return java.util.Collections.unmodifiableList(
            instance.getDataList());
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public int getDataCount() {
        return instance.getDataCount();
      }/**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public com.fula.yohee.pb.Info.History.Item getData(int index) {
        return instance.getData(index);
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder setData(
          int index, com.fula.yohee.pb.Info.History.Item value) {
        copyOnWrite();
        instance.setData(index, value);
        return this;
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder setData(
          int index, com.fula.yohee.pb.Info.History.Item.Builder builderForValue) {
        copyOnWrite();
        instance.setData(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder addData(com.fula.yohee.pb.Info.History.Item value) {
        copyOnWrite();
        instance.addData(value);
        return this;
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder addData(
          int index, com.fula.yohee.pb.Info.History.Item value) {
        copyOnWrite();
        instance.addData(index, value);
        return this;
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder addData(
          com.fula.yohee.pb.Info.History.Item.Builder builderForValue) {
        copyOnWrite();
        instance.addData(builderForValue);
        return this;
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder addData(
          int index, com.fula.yohee.pb.Info.History.Item.Builder builderForValue) {
        copyOnWrite();
        instance.addData(index, builderForValue);
        return this;
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends com.fula.yohee.pb.Info.History.Item> values) {
        copyOnWrite();
        instance.addAllData(values);
        return this;
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder clearData() {
        copyOnWrite();
        instance.clearData();
        return this;
      }
      /**
       * <pre>
       *the history items array.
       * </pre>
       *
       * <code>repeated .base.History.Item data = 1;</code>
       */
      public Builder removeData(int index) {
        copyOnWrite();
        instance.removeData(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:base.History)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fula.yohee.pb.Info.History();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          data_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fula.yohee.pb.Info.History other = (com.fula.yohee.pb.Info.History) arg1;
          data_= visitor.visitList(data_, other.data_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!data_.isModifiable()) {
                    data_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(data_);
                  }
                  data_.add(
                      input.readMessage(com.fula.yohee.pb.Info.History.Item.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fula.yohee.pb.Info.History.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:base.History)
    private static final com.fula.yohee.pb.Info.History DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new History();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fula.yohee.pb.Info.History getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<History> PARSER;

    public static com.google.protobuf.Parser<History> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserPreferOrBuilder extends
      // @@protoc_insertion_point(interface_extends:base.UserPrefer)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */
    int getSettingsCount();
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */
    boolean containsSettings(
        java.lang.String key);
    /**
     * Use {@link #getSettingsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getSettings();
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getSettingsMap();
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */

    int getSettingsOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */

    int getSettingsOrThrow(
        java.lang.String key);

    /**
     * <pre>
     *proxy host
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    java.lang.String getHost();
    /**
     * <pre>
     *proxy host
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();
  }
  /**
   * Protobuf type {@code base.UserPrefer}
   */
  public  static final class UserPrefer extends
      com.google.protobuf.GeneratedMessageLite<
          UserPrefer, UserPrefer.Builder> implements
      // @@protoc_insertion_point(message_implements:base.UserPrefer)
      UserPreferOrBuilder {
    private UserPrefer() {
      host_ = "";
    }
    private int bitField0_;
    public static final int SETTINGS_FIELD_NUMBER = 1;
    private static final class SettingsDefaultEntryHolder {
      static final com.google.protobuf.MapEntryLite<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntryLite
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.UINT32,
                  0);
    }
    private com.google.protobuf.MapFieldLite<
        java.lang.String, java.lang.Integer> settings_ =
            com.google.protobuf.MapFieldLite.emptyMapField();
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Integer>
    internalGetSettings() {
      return settings_;
    }
    private com.google.protobuf.MapFieldLite<java.lang.String, java.lang.Integer>
    internalGetMutableSettings() {
      if (!settings_.isMutable()) {
        settings_ = settings_.mutableCopy();
      }
      return settings_;
    }

    public int getSettingsCount() {
      return internalGetSettings().size();
    }
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */

    public boolean containsSettings(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetSettings().containsKey(key);
    }
    /**
     * Use {@link #getSettingsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getSettings() {
      return getSettingsMap();
    }
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getSettingsMap() {
      return java.util.Collections.unmodifiableMap(
          internalGetSettings());
    }
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */

    public int getSettingsOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSettings();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */

    public int getSettingsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetSettings();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    /**
     * <code>map&lt;string, uint32&gt; settings = 1;</code>
     */
    private java.util.Map<java.lang.String, java.lang.Integer>
    getMutableSettingsMap() {
      return internalGetMutableSettings();
    }

    public static final int HOST_FIELD_NUMBER = 2;
    private java.lang.String host_;
    /**
     * <pre>
     *proxy host
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    public java.lang.String getHost() {
      return host_;
    }
    /**
     * <pre>
     *proxy host
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(host_);
    }
    /**
     * <pre>
     *proxy host
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    private void setHost(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      host_ = value;
    }
    /**
     * <pre>
     *proxy host
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    private void clearHost() {
      
      host_ = getDefaultInstance().getHost();
    }
    /**
     * <pre>
     *proxy host
     * </pre>
     *
     * <code>optional string host = 2;</code>
     */
    private void setHostBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      host_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetSettings().entrySet()) {
        SettingsDefaultEntryHolder.defaultEntry.serializeTo(
            output, 1, entry.getKey(), entry.getValue());
      }
      if (!host_.isEmpty()) {
        output.writeString(2, getHost());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetSettings().entrySet()) {
        size += SettingsDefaultEntryHolder.defaultEntry.computeMessageSize(
          1, entry.getKey(), entry.getValue());
      }
      if (!host_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getHost());
      }
      memoizedSerializedSize = size;
      return size;
    }

    public static com.fula.yohee.pb.Info.UserPrefer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static com.fula.yohee.pb.Info.UserPrefer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.fula.yohee.pb.Info.UserPrefer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code base.UserPrefer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          com.fula.yohee.pb.Info.UserPrefer, Builder> implements
        // @@protoc_insertion_point(builder_implements:base.UserPrefer)
        com.fula.yohee.pb.Info.UserPreferOrBuilder {
      // Construct using com.fula.yohee.pb.Info.UserPrefer.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }



      public int getSettingsCount() {
        return instance.getSettingsMap().size();
      }
      /**
       * <code>map&lt;string, uint32&gt; settings = 1;</code>
       */

      public boolean containsSettings(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return instance.getSettingsMap().containsKey(key);
      }

      public Builder clearSettings() {
        copyOnWrite();
        instance.getMutableSettingsMap().clear();
        return this;
      }
      /**
       * <code>map&lt;string, uint32&gt; settings = 1;</code>
       */

      public Builder removeSettings(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        copyOnWrite();
        instance.getMutableSettingsMap().remove(key);
        return this;
      }
      /**
       * Use {@link #getSettingsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getSettings() {
        return getSettingsMap();
      }
      /**
       * <code>map&lt;string, uint32&gt; settings = 1;</code>
       */
      public java.util.Map<java.lang.String, java.lang.Integer> getSettingsMap() {
        return java.util.Collections.unmodifiableMap(
            instance.getSettingsMap());
      }
      /**
       * <code>map&lt;string, uint32&gt; settings = 1;</code>
       */

      public int getSettingsOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            instance.getSettingsMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, uint32&gt; settings = 1;</code>
       */

      public int getSettingsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            instance.getSettingsMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      /**
       * <code>map&lt;string, uint32&gt; settings = 1;</code>
       */
      public Builder putSettings(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        copyOnWrite();
        instance.getMutableSettingsMap().put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, uint32&gt; settings = 1;</code>
       */
      public Builder putAllSettings(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        copyOnWrite();
        instance.getMutableSettingsMap().putAll(values);
        return this;
      }

      /**
       * <pre>
       *proxy host
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public java.lang.String getHost() {
        return instance.getHost();
      }
      /**
       * <pre>
       *proxy host
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        return instance.getHostBytes();
      }
      /**
       * <pre>
       *proxy host
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        copyOnWrite();
        instance.setHost(value);
        return this;
      }
      /**
       * <pre>
       *proxy host
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public Builder clearHost() {
        copyOnWrite();
        instance.clearHost();
        return this;
      }
      /**
       * <pre>
       *proxy host
       * </pre>
       *
       * <code>optional string host = 2;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setHostBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:base.UserPrefer)
    }
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new com.fula.yohee.pb.Info.UserPrefer();
        }
        case IS_INITIALIZED: {
          return DEFAULT_INSTANCE;
        }
        case MAKE_IMMUTABLE: {
          settings_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          com.fula.yohee.pb.Info.UserPrefer other = (com.fula.yohee.pb.Info.UserPrefer) arg1;
          settings_ = visitor.visitMap(
              settings_, other.internalGetSettings());
          host_ = visitor.visitString(!host_.isEmpty(), host_,
              !other.host_.isEmpty(), other.host_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!input.skipField(tag)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!settings_.isMutable()) {
                    settings_ = settings_.mutableCopy();
                  }
                  SettingsDefaultEntryHolder.defaultEntry.parseInto(settings_, input, extensionRegistry);  break;
                }
                case 18: {
                  String s = input.readStringRequireUtf8();

                  host_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (com.fula.yohee.pb.Info.UserPrefer.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:base.UserPrefer)
    private static final com.fula.yohee.pb.Info.UserPrefer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserPrefer();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static com.fula.yohee.pb.Info.UserPrefer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<UserPrefer> PARSER;

    public static com.google.protobuf.Parser<UserPrefer> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
